name: sandwich_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.9.2"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.15
  go_router: ^17.0.0
  shared_preferences: ^2.5.3
  provider: ^6.0.5
  sqflite: ^2.3.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  image: ^4.6.0
  sqflite_common_ffi: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
    - assets/images/chickenTeriyaki_footlong.png
    - assets/images/chickenTeriyaki_six_inch.png
    - assets/images/logo.png
    - assets/images/meatballMarinara_footlong.png
    - assets/images/meatballMarinara_six_inch.png
    - assets/images/tunaMelt_footlong.png
    - assets/images/tunaMelt_six_inch.png
    - assets/images/veggieDelight_footlong.png
    - assets/images/veggieDelight_six_inch.png
    - assets/sandwiches.json

flutter_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
  image_path: "assets/images/logo.png"
